server:
  port: 4040
spring:
  application:
    name: loglens
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 2908
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
grpc:
  server:
    port: 7000